# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MqttServer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(581, 593)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.state_bar = QtWidgets.QFrame(self.centralwidget)
        self.state_bar.setGeometry(QtCore.QRect(110, 60, 320, 410))
        self.state_bar.setStyleSheet("QFrame{\n"
"    background-color: #84b6c0;\n"
"    border-radius:15px;\n"
"\n"
"\n"
"}\n"
"")
        self.state_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.state_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.state_bar.setObjectName("state_bar")
        self.about_btn = QtWidgets.QToolButton(self.state_bar)
        self.about_btn.setGeometry(QtCore.QRect(90, 5, 36, 36))
        self.about_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}\n"
"QToolButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.about_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icons/about_light.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about_btn.setIcon(icon)
        self.about_btn.setIconSize(QtCore.QSize(60, 60))
        self.about_btn.setObjectName("about_btn")
        self.wifi_lab = QtWidgets.QLabel(self.state_bar)
        self.wifi_lab.setGeometry(QtCore.QRect(190, 5, 36, 36))
        self.wifi_lab.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    image: url(:/img/icons/not_network.png);\n"
"}")
        self.wifi_lab.setText("")
        self.wifi_lab.setObjectName("wifi_lab")
        self.close_btn = QtWidgets.QToolButton(self.state_bar)
        self.close_btn.setGeometry(QtCore.QRect(270, 5, 36, 36))
        self.close_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}\n"
"QToolButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.close_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon1)
        self.close_btn.setIconSize(QtCore.QSize(60, 60))
        self.close_btn.setObjectName("close_btn")
        self.set_btn = QtWidgets.QToolButton(self.state_bar)
        self.set_btn.setGeometry(QtCore.QRect(10, 5, 36, 36))
        self.set_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}\n"
"QToolButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.set_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/icons/set_light.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_btn.setIcon(icon2)
        self.set_btn.setIconSize(QtCore.QSize(60, 60))
        self.set_btn.setObjectName("set_btn")
        self.conf_btn = QtWidgets.QToolButton(self.state_bar)
        self.conf_btn.setGeometry(QtCore.QRect(50, 5, 36, 36))
        self.conf_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}\n"
"QToolButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.conf_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/icons/file_ligth.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.conf_btn.setIcon(icon3)
        self.conf_btn.setIconSize(QtCore.QSize(60, 60))
        self.conf_btn.setObjectName("conf_btn")
        self.min_btn = QtWidgets.QToolButton(self.state_bar)
        self.min_btn.setGeometry(QtCore.QRect(230, 5, 36, 36))
        self.min_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}\n"
"QToolButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.min_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/icons/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min_btn.setIcon(icon4)
        self.min_btn.setIconSize(QtCore.QSize(60, 60))
        self.min_btn.setObjectName("min_btn")
        self.frame = QtWidgets.QFrame(self.state_bar)
        self.frame.setGeometry(QtCore.QRect(10, 50, 300, 351))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color:#cae0e4;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ip_text = QtWidgets.QLineEdit(self.frame)
        self.ip_text.setGeometry(QtCore.QRect(80, 10, 113, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ip_text.setFont(font)
        self.ip_text.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"    border-bottom:1px solid back;\n"
"}")
        self.ip_text.setInputMask("")
        self.ip_text.setText("")
        self.ip_text.setObjectName("ip_text")
        self.connect_lab = QtWidgets.QLabel(self.frame)
        self.connect_lab.setGeometry(QtCore.QRect(10, 15, 60, 60))
        self.connect_lab.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    image: url(:/img/icons/disconnect01.png);\n"
"}")
        self.connect_lab.setText("")
        self.connect_lab.setObjectName("connect_lab")
        self.open_server_btn = QtWidgets.QPushButton(self.frame)
        self.open_server_btn.setGeometry(QtCore.QRect(200, 10, 91, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.open_server_btn.setFont(font)
        self.open_server_btn.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background-color:#e3f3f7;\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:5px;\n"
"    background-color:#80a3a2;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/icons/connect02.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_server_btn.setIcon(icon5)
        self.open_server_btn.setIconSize(QtCore.QSize(24, 24))
        self.open_server_btn.setObjectName("open_server_btn")
        self.logs_text = QtWidgets.QTextEdit(self.frame)
        self.logs_text.setGeometry(QtCore.QRect(10, 90, 281, 251))
        self.logs_text.setStyleSheet("QTextEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:none;\n"
"}")
        self.logs_text.setObjectName("logs_text")
        self.port_text = QtWidgets.QLineEdit(self.frame)
        self.port_text.setGeometry(QtCore.QRect(80, 50, 113, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.port_text.setFont(font)
        self.port_text.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"    border-bottom:1px solid back;\n"
"}")
        self.port_text.setObjectName("port_text")
        self.close_server_btn = QtWidgets.QPushButton(self.frame)
        self.close_server_btn.setGeometry(QtCore.QRect(200, 50, 91, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.close_server_btn.setFont(font)
        self.close_server_btn.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background-color:#e3f3f7;\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:5px;\n"
"    background-color:#80a3a2;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/icons/disconnect02.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_server_btn.setIcon(icon6)
        self.close_server_btn.setIconSize(QtCore.QSize(24, 24))
        self.close_server_btn.setObjectName("close_server_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ip_text.setPlaceholderText(_translate("MainWindow", "请输入IP地址"))
        self.open_server_btn.setText(_translate("MainWindow", "启动服务"))
        self.port_text.setPlaceholderText(_translate("MainWindow", "请输入端口号"))
        self.close_server_btn.setText(_translate("MainWindow", "关闭服务"))

