# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(170, 50, 271, 231))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(218, 218, 218);\n"
"border-radius:15px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.min_btn = QtWidgets.QToolButton(self.frame)
        self.min_btn.setGeometry(QtCore.QRect(190, 5, 36, 36))
        self.min_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}\n"
"QToolButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.min_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icons/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min_btn.setIcon(icon)
        self.min_btn.setIconSize(QtCore.QSize(60, 60))
        self.min_btn.setObjectName("min_btn")
        self.close_btn = QtWidgets.QToolButton(self.frame)
        self.close_btn.setGeometry(QtCore.QRect(230, 5, 36, 36))
        self.close_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}\n"
"QToolButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.close_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon1)
        self.close_btn.setIconSize(QtCore.QSize(60, 60))
        self.close_btn.setObjectName("close_btn")
        self.about_lab = QtWidgets.QLabel(self.frame)
        self.about_lab.setGeometry(QtCore.QRect(10, 5, 36, 36))
        self.about_lab.setStyleSheet("QLabel{\n"
"    image: url(:/img/icons/about_dark.png);\n"
"    border:none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.about_lab.setText("")
        self.about_lab.setObjectName("about_lab")
        self.github_lab_2 = QtWidgets.QLabel(self.frame)
        self.github_lab_2.setGeometry(QtCore.QRect(40, 60, 201, 101))
        self.github_lab_2.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    font: 57 15pt \"Alibaba PuHuiTi 3.0\";\n"
"}")
        self.github_lab_2.setObjectName("github_lab_2")
        self.github_btn = QtWidgets.QToolButton(self.frame)
        self.github_btn.setGeometry(QtCore.QRect(90, 180, 36, 36))
        self.github_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}")
        self.github_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/icons/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.github_btn.setIcon(icon2)
        self.github_btn.setIconSize(QtCore.QSize(60, 60))
        self.github_btn.setObjectName("github_btn")
        self.csdn_btn = QtWidgets.QToolButton(self.frame)
        self.csdn_btn.setGeometry(QtCore.QRect(150, 180, 36, 36))
        self.csdn_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}")
        self.csdn_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/icons/csdn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.csdn_btn.setIcon(icon3)
        self.csdn_btn.setIconSize(QtCore.QSize(60, 60))
        self.csdn_btn.setObjectName("csdn_btn")

        self.retranslateUi(Dialog)
        self.close_btn.clicked.connect(Dialog.close_dialog) # type: ignore
        self.min_btn.clicked.connect(Dialog.min_dialog) # type: ignore
        self.csdn_btn.clicked.connect(Dialog.open_csdn) # type: ignore
        self.github_btn.clicked.connect(Dialog.open_github) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.github_lab_2.setText(_translate("Dialog", "MQTT 服务器管理工具\n"
"版本: 0.1.0\n"
"作者: LeurDeLis"))
# import icon_rc
