# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MqttServer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(502, 530)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.state_bar = QtWidgets.QFrame(self.centralwidget)
        self.state_bar.setGeometry(QtCore.QRect(80, 20, 320, 455))
        self.state_bar.setStyleSheet("QFrame{\n"
"    background-color:#c9d6df;\n"
"     border-radius:15px;\n"
"}\n"
"")
        self.state_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.state_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.state_bar.setObjectName("state_bar")
        self.close_btn = QtWidgets.QToolButton(self.state_bar)
        self.close_btn.setGeometry(QtCore.QRect(280, 5, 36, 36))
        self.close_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}\n"
"QToolButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.close_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon)
        self.close_btn.setIconSize(QtCore.QSize(60, 60))
        self.close_btn.setObjectName("close_btn")
        self.min_btn = QtWidgets.QToolButton(self.state_bar)
        self.min_btn.setGeometry(QtCore.QRect(240, 5, 36, 36))
        self.min_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}\n"
"QToolButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.min_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/icons/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min_btn.setIcon(icon1)
        self.min_btn.setIconSize(QtCore.QSize(60, 60))
        self.min_btn.setObjectName("min_btn")
        self.frame = QtWidgets.QFrame(self.state_bar)
        self.frame.setGeometry(QtCore.QRect(10, 45, 301, 401))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color:#d6e6f2;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ip_text = QtWidgets.QLineEdit(self.frame)
        self.ip_text.setGeometry(QtCore.QRect(80, 55, 113, 30))
        font = QtGui.QFont()
        font.setFamily("系统字体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ip_text.setFont(font)
        self.ip_text.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"    border-bottom:1px solid back;\n"
"font: 12pt \"系统字体\";\n"
"}")
        self.ip_text.setInputMask("")
        self.ip_text.setText("")
        self.ip_text.setObjectName("ip_text")
        self.connect_lab = QtWidgets.QLabel(self.frame)
        self.connect_lab.setGeometry(QtCore.QRect(10, 60, 60, 60))
        self.connect_lab.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    image: url(:/img/icons/disconnect01.png);\n"
"}")
        self.connect_lab.setText("")
        self.connect_lab.setObjectName("connect_lab")
        self.open_server_btn = QtWidgets.QPushButton(self.frame)
        self.open_server_btn.setGeometry(QtCore.QRect(200, 55, 91, 36))
        font = QtGui.QFont()
        font.setFamily("系统字体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.open_server_btn.setFont(font)
        self.open_server_btn.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background-color:#e3f3f7;\n"
"font: 11pt \"系统字体\";\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:5px;\n"
"    background-color:#80a3a2;\n"
"font: 11pt \"系统字体\";\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/icons/connect02.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_server_btn.setIcon(icon2)
        self.open_server_btn.setIconSize(QtCore.QSize(24, 24))
        self.open_server_btn.setObjectName("open_server_btn")
        self.logs_text = QtWidgets.QTextEdit(self.frame)
        self.logs_text.setGeometry(QtCore.QRect(10, 140, 281, 251))
        self.logs_text.setStyleSheet("QTextEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:none;\n"
"    font: 57 12pt \"Alibaba PuHuiTi 3.0\";\n"
"}")
        self.logs_text.setObjectName("logs_text")
        self.port_text = QtWidgets.QLineEdit(self.frame)
        self.port_text.setGeometry(QtCore.QRect(80, 95, 113, 30))
        font = QtGui.QFont()
        font.setFamily("系统字体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.port_text.setFont(font)
        self.port_text.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"    border-bottom:1px solid back;\n"
"    font: 12pt \"系统字体\";\n"
"}")
        self.port_text.setObjectName("port_text")
        self.close_server_btn = QtWidgets.QPushButton(self.frame)
        self.close_server_btn.setGeometry(QtCore.QRect(200, 95, 91, 36))
        font = QtGui.QFont()
        font.setFamily("系统字体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.close_server_btn.setFont(font)
        self.close_server_btn.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background-color:#e3f3f7;\n"
"font: 11pt \"系统字体\";\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:5px;\n"
"    background-color:#80a3a2;\n"
"font: 11pt \"系统字体\";\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/icons/disconnect02.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_server_btn.setIcon(icon3)
        self.close_server_btn.setIconSize(QtCore.QSize(24, 24))
        self.close_server_btn.setObjectName("close_server_btn")
        self.wifi_lab = QtWidgets.QLabel(self.frame)
        self.wifi_lab.setGeometry(QtCore.QRect(250, 5, 36, 36))
        self.wifi_lab.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    image: url(:/img/icons/not_network.png);\n"
"}")
        self.wifi_lab.setText("")
        self.wifi_lab.setObjectName("wifi_lab")
        self.about_btn = QtWidgets.QToolButton(self.frame)
        self.about_btn.setGeometry(QtCore.QRect(50, 5, 36, 36))
        self.about_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}\n"
"QToolButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.about_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/icons/about_dark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about_btn.setIcon(icon4)
        self.about_btn.setIconSize(QtCore.QSize(60, 60))
        self.about_btn.setObjectName("about_btn")
        self.set_btn = QtWidgets.QToolButton(self.frame)
        self.set_btn.setGeometry(QtCore.QRect(10, 5, 36, 36))
        self.set_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}\n"
"QToolButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.set_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/icons/set_light.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_btn.setIcon(icon5)
        self.set_btn.setIconSize(QtCore.QSize(60, 60))
        self.set_btn.setObjectName("set_btn")
        self.wifi_lab_2 = QtWidgets.QLabel(self.state_bar)
        self.wifi_lab_2.setGeometry(QtCore.QRect(10, 5, 36, 36))
        self.wifi_lab_2.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    image: url(:/img/icons/app_icon.png);\n"
"}")
        self.wifi_lab_2.setText("")
        self.wifi_lab_2.setObjectName("wifi_lab_2")
        self.wifi_lab_3 = QtWidgets.QLabel(self.state_bar)
        self.wifi_lab_3.setGeometry(QtCore.QRect(50, 5, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.wifi_lab_3.setFont(font)
        self.wifi_lab_3.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    font: 87 12pt \"Arial Black\";\n"
"}\n"
"")
        self.wifi_lab_3.setObjectName("wifi_lab_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.close_btn.clicked.connect(MainWindow.close_app) # type: ignore
        self.min_btn.clicked.connect(MainWindow.min_app) # type: ignore
        self.open_server_btn.clicked.connect(MainWindow.connect_btn) # type: ignore
        self.close_server_btn.clicked.connect(MainWindow.disconnect_btn) # type: ignore
        self.set_btn.clicked.connect(MainWindow.setting) # type: ignore
        self.about_btn.clicked.connect(MainWindow.about_app) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ip_text.setPlaceholderText(_translate("MainWindow", "请输入IP地址"))
        self.open_server_btn.setText(_translate("MainWindow", "启动服务"))
        self.port_text.setPlaceholderText(_translate("MainWindow", "请输入端口号"))
        self.close_server_btn.setText(_translate("MainWindow", "关闭服务"))
        self.wifi_lab_3.setText(_translate("MainWindow", "MQTT Server"))
import Source.icon_rc
