# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(431, 359)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(60, 50, 291, 231))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color:#c9d6df;\n"
"border-radius:10px;\n"
"}\n"
"/*玻璃效果\n"
"QFrame \n"
"{\n"
"    background-color: rgba(255, 255, 255, 180);\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgba(255, 255, 255, 100);\n"
"}*/\n"
"QGroupBox{\n"
"    background-color: #f0f5f9;\n"
"    border:none;\n"
"font: 13pt \"系统字体\";\n"
"border-radius:10px;\n"
"}\n"
"QLabel{\n"
"        border:none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    font: 87 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 121, 171))
        self.groupBox.setStyleSheet("")
        self.groupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(12, 24, 12, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.set_theme1_btn = QtWidgets.QPushButton(self.groupBox)
        self.set_theme1_btn.setMinimumSize(QtCore.QSize(25, 36))
        self.set_theme1_btn.setStyleSheet("QPushButton{\n"
"\n"
"border-radius:10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 13pt \"系统字体\";\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}")
        self.set_theme1_btn.setObjectName("set_theme1_btn")
        self.verticalLayout.addWidget(self.set_theme1_btn)
        self.set_theme2_btn = QtWidgets.QPushButton(self.groupBox)
        self.set_theme2_btn.setMinimumSize(QtCore.QSize(0, 36))
        self.set_theme2_btn.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 13pt \"系统字体\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}")
        self.set_theme2_btn.setObjectName("set_theme2_btn")
        self.verticalLayout.addWidget(self.set_theme2_btn)
        self.set_theme3_btn = QtWidgets.QPushButton(self.groupBox)
        self.set_theme3_btn.setMinimumSize(QtCore.QSize(0, 36))
        self.set_theme3_btn.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"    background-color: #c9d6df;\n"
"    font: 13pt \"系统字体\";\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}")
        self.set_theme3_btn.setObjectName("set_theme3_btn")
        self.verticalLayout.addWidget(self.set_theme3_btn)
        self.min_btn = QtWidgets.QToolButton(self.frame)
        self.min_btn.setGeometry(QtCore.QRect(210, 5, 36, 36))
        self.min_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}\n"
"QToolButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.min_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icons/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min_btn.setIcon(icon)
        self.min_btn.setIconSize(QtCore.QSize(60, 60))
        self.min_btn.setObjectName("min_btn")
        self.close_btn = QtWidgets.QToolButton(self.frame)
        self.close_btn.setGeometry(QtCore.QRect(250, 5, 36, 36))
        self.close_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}\n"
"QToolButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.close_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon1)
        self.close_btn.setIconSize(QtCore.QSize(60, 60))
        self.close_btn.setObjectName("close_btn")
        self.wifi_lab_2 = QtWidgets.QLabel(self.frame)
        self.wifi_lab_2.setGeometry(QtCore.QRect(10, 5, 36, 36))
        self.wifi_lab_2.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    image: url(:/img/icons/app_icon.png);\n"
"}")
        self.wifi_lab_2.setText("")
        self.wifi_lab_2.setObjectName("wifi_lab_2")
        self.path_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.path_lineEdit.setGeometry(QtCore.QRect(140, 80, 110, 31))
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.conf_btn = QtWidgets.QToolButton(self.frame)
        self.conf_btn.setGeometry(QtCore.QRect(250, 80, 31, 31))
        self.conf_btn.setStyleSheet("QToolButton{\n"
"    border:none\n"
"}\n"
"QToolButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.conf_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/icons/file_ligth.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.conf_btn.setIcon(icon2)
        self.conf_btn.setIconSize(QtCore.QSize(60, 60))
        self.conf_btn.setObjectName("conf_btn")
        self.save_conf_btn = QtWidgets.QPushButton(self.frame)
        self.save_conf_btn.setGeometry(QtCore.QRect(140, 130, 141, 36))
        self.save_conf_btn.setMinimumSize(QtCore.QSize(25, 36))
        self.save_conf_btn.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"font: 13pt \"系统字体\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius:10px;\n"
"    background-color:#e3f3f7;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}")
        self.save_conf_btn.setObjectName("save_conf_btn")
        self.default_conf_btn = QtWidgets.QPushButton(self.frame)
        self.default_conf_btn.setGeometry(QtCore.QRect(140, 180, 141, 36))
        self.default_conf_btn.setMinimumSize(QtCore.QSize(25, 36))
        self.default_conf_btn.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 13pt \"系统字体\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius:10px;\n"
"    background-color:#e3f3f7;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}")
        self.default_conf_btn.setObjectName("default_conf_btn")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 50, 141, 25))
        self.label.setStyleSheet("font: 13pt \"系统字体\";")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.close_btn.clicked.connect(Dialog.close_dialog) # type: ignore
        self.min_btn.clicked.connect(Dialog.min_dialog) # type: ignore
        self.set_theme1_btn.clicked.connect(Dialog.set_theme_one) # type: ignore
        self.set_theme2_btn.clicked.connect(Dialog.set_theme_two) # type: ignore
        self.set_theme3_btn.clicked.connect(Dialog.set_theme_three) # type: ignore
        self.conf_btn.clicked.connect(Dialog.file_path) # type: ignore
        self.save_conf_btn.clicked.connect(Dialog.save_conf) # type: ignore
        self.default_conf_btn.clicked.connect(Dialog.default_conf) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "设置"))
        self.groupBox.setTitle(_translate("Dialog", "Theme"))
        self.set_theme1_btn.setText(_translate("Dialog", "白色主题"))
        self.set_theme2_btn.setText(_translate("Dialog", "黑色主题"))
        self.set_theme3_btn.setText(_translate("Dialog", "默认主题"))
        self.save_conf_btn.setText(_translate("Dialog", "保存配置"))
        self.default_conf_btn.setText(_translate("Dialog", "恢复默认"))
        self.label.setText(_translate("Dialog", "ConfigFilePath:"))
# import icon_rc
